# Example: Deploy to multidev on pull request

name: Deploy to Pantheon Multidev

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  deploy_multidev:
    uses: Square360/shared-pantheon-workflows/.github/workflows/reusable-deploy-multidev.yml@main
    with:
      pantheon_site: your-site-name
      target_env: pr-${{ github.event.pull_request.number }}
      create_multidev: true
      clone_content: false
      delete_multidev_after: false
    secrets:
      PANTHEON_SSH_KEY: ${{ secrets.PANTHEON_SSH_KEY }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}