# Example workflow showing how to use Slack notifications
# This file should be placed in .github/workflows/ in your consuming repository

name: Deploy to Pantheon with Slack Notifications

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-main:
    if: github.event_name == 'push'
    uses: Square360/shared-pantheon-workflows/.github/workflows/reusable-deploy-pantheon.yml@main
    with:
      pantheon_site: ${{ vars.PANTHEON_SITE }}
      target_env: "dev"
      slack_channel: ${{ vars.SLACK_CHANNEL }}
      slack_webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
    secrets:
      PANTHEON_SSH_KEY: ${{ secrets.PANTHEON_SSH_KEY }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      CI_GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}

  deploy-multidev:
    if: github.event_name == 'pull_request'
    uses: Square360/shared-pantheon-workflows/.github/workflows/reusable-deploy-multidev.yml@main
    with:
      pantheon_site: ${{ vars.PANTHEON_SITE }}
      target_env: "pr-${{ github.event.number }}"
      slack_channel: ${{ vars.SLACK_CHANNEL }}
      slack_webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
    secrets:
      PANTHEON_SSH_KEY: ${{ secrets.PANTHEON_SSH_KEY }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}